CREATE TABLE UNITATI 
(
	ID_UNITATE NUMBER(2) PRIMARY KEY,
	DENUMIRE VARCHAR2(30),
	LOCATIE VARCHAR2(30)
);

CREATE TABLE TIP_INGHETATA
(
	ID_TIP NUMBER(2) PRIMARY KEY,
	DEN_TIP VARCHAR2(30),
	PRET NUMBER(7,2)
);


CREATE TABLE MENIU_UNITATI
(
	ID_UNITATE NUMBER(2),
	ID_TIP NUMBER(2),
	DISCOUNT NUMBER(5,2),
	CONSTRAINT PK_MENIU PRIMARY KEY (ID_UNITATE, ID_TIP),
	CONSTRAINT FK_MENIU_UNITATI FOREIGN KEY (ID_UNITATE) REFERENCES UNITATI(ID_UNITATE),
	CONSTRAINT FK_MENIU_TIP_INGHETATA FOREIGN KEY (ID_TIP) REFERENCES TIP_INGHETATA(ID_TIP)
);

INSERT INTO UNITATI VALUES(1,'53','AFI');
INSERT INTO UNITATI (ID_UNITATE, DENUMIRE, LOCATIE) VALUES (2,'78','DRUMUL TABEREI');
INSERT INTO UNITATI (ID_UNITATE, DENUMIRE) VALUES (3,'79');
INSERT INTO UNITATI VALUES (4,'80',NULL);

INSERT INTO TIP_INGHETATA (ID_TIP, DEN_TIP, PRET) VALUES (1,'OREO',1.99);
INSERT INTO TIP_INGHETATA (ID_TIP, DEN_TIP, PRET) VALUES (2,'VANILIE',0.99);
INSERT INTO TIP_INGHETATA (ID_TIP, DEN_TIP, PRET) VALUES (3,'VAFA',0.5);

INSERT INTO MENIU_UNITATI (ID_UNITATE, ID_TIP, DISCOUNT) VALUES (1, 1, 70);
INSERT INTO MENIU_UNITATI (ID_UNITATE, ID_TIP, DISCOUNT) VALUES (2, 3, 0);
INSERT INTO MENIU_UNITATI (ID_UNITATE, ID_TIP, DISCOUNT) VALUES (1, 2, 40);

DESC UNITATI;
DESC TIP_INGHETATA;
DESC MENIU_UNITATI;

SELECT ID_UNITATE, DENUMIRE FROM UNITATI;

SELECT * FROM TIP_INGHETATA;

SELECT DISCOUNT FROM MENIU_UNITATI;



DROP TABLE MENIU_UNITATI;
DROP TABLE TIP_INGHETATA;
DROP TABLE UNITATI;